spring:
  profiles:
    active: dev
  application:
    name: cars-api-gateway
  cloud:
    gateway:
      routes:
        - id: users-get
          uri: lb://users
          predicates:
            - Path=/users/**
            - Method=GET
        - id: users-post
          uri: lb://users
          predicates:
            - Path=/users/**
            - Method=POST
        - id: test
          uri: lb://accounts
          predicates:
            - Path=/accounts/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9191/eureka
  instance:
    preferIpAddress: false
